-- Run in Supabase SQL editor so the Express backend can read/write
-- while using the anon key (or switch backend to SUPABASE_SERVICE_ROLE_KEY).
-- This app uses its own JWT auth, not Supabase Auth.

-- Core tenant tables
ALTER TABLE IF EXISTS schools DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS students DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS staffs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS nonstaffs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS messages DISABLE ROW LEVEL SECURITY;

-- Billing / wallets / SMS (from supabase_core_billing.sql)
ALTER TABLE IF EXISTS subscription_payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS school_wallets DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS wallet_accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS wallet_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS platform_sms_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS platform_sms_sales DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS school_sms_balances DISABLE ROW LEVEL SECURITY;

-- Optional academic tables
ALTER TABLE IF EXISTS fee_payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS report_cards DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS classes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS class_fees DISABLE ROW LEVEL SECURITY;
